// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPLogicaWebApi.DATA.Models;

public partial class Autenticacion
{
    public int IdAutenticado { get; set; }

    public Guid IdUsuario { get; set; }

    public int IdRol { get; set; }

    public virtual Role IdRolNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}