// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPLogicaWebApi.DATA.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string NomCliente { get; set; }

    public string ApeCliente { get; set; }

    public string Domicilio { get; set; }

    public int Dni { get; set; }

    public string Teléfono { get; set; }

    public bool Estado { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}