// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPLogicaWebApi.DATA.Models;

public partial class Credenciale
{
    public Guid IdCredencial { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}