// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TPLogicaWebApi.DATA.Models;

public partial class DetalleFactura
{
    public int IdDetalleFacturas { get; set; }

    public int NroFactura { get; set; }

    public int IdProducto { get; set; }

    public decimal PrecioUnitario { get; set; }

    public int Cantidad { get; set; }

    public string Observ { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }

    [ForeignKey("IdProducto")]
    public virtual Producto IdProductoNavigation { get; set; }
}