// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPLogicaWebApi.DATA.Models;

public partial class Empleado
{
    public int IdEmpleado { get; set; }

    public string NomEmp { get; set; }

    public string ApeEmp { get; set; }

    public string Domicilio { get; set; }

    public int Dni { get; set; }

    public string Teléfono { get; set; }

    public bool Estado { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}