// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPLogicaWebApi.DATA.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public string TipoFactura { get; set; }

    public int IdEmpleado { get; set; }

    public DateOnly FechaFactura { get; set; }

    public int IdCliente { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }
}