// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TPLogicaWebApi.DATA.Models;

public partial class FarmaciaTPLogica1Context : DbContext
{
    public FarmaciaTPLogica1Context(DbContextOptions<FarmaciaTPLogica1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Autenticacion> Autenticacions { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Credenciale> Credenciales { get; set; }

    public virtual DbSet<DetalleFactura> DetalleFacturas { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Autenticacion>(entity =>
        {
            entity.HasKey(e => e.IdAutenticado).HasName("PK__Autentic__358880BFBA3CA88F");

            entity.ToTable("Autenticacion");

            entity.Property(e => e.IdAutenticado).HasColumnName("idAutenticado");
            entity.Property(e => e.IdRol).HasColumnName("idRol");
            entity.Property(e => e.IdUsuario).HasColumnName("idUsuario");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.Autenticacions)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_idRol");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Autenticacions)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_idUsuario");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__Clientes__885457EE4B81245E");

            entity.Property(e => e.IdCliente).HasColumnName("idCliente");
            entity.Property(e => e.ApeCliente)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("apeCliente");
            entity.Property(e => e.Dni).HasColumnName("dni");
            entity.Property(e => e.Domicilio)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("domicilio");
            entity.Property(e => e.Estado).HasColumnName("estado");
            entity.Property(e => e.NomCliente)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("nomCliente");
            entity.Property(e => e.Teléfono)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("teléfono");
        });

        modelBuilder.Entity<Credenciale>(entity =>
        {
            entity.HasKey(e => e.IdCredencial);

            entity.Property(e => e.IdCredencial)
                .ValueGeneratedNever()
                .HasColumnName("idCredencial");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("password");
        });

        modelBuilder.Entity<DetalleFactura>(entity =>
        {
            entity.HasKey(e => e.IdDetalleFacturas).HasName("PK__detalleF__0D8C4135DAAEE85E");

            entity.ToTable("detalleFacturas");

            entity.Property(e => e.IdDetalleFacturas).HasColumnName("idDetalleFacturas");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdProducto).HasColumnName("idProducto");
            entity.Property(e => e.NroFactura).HasColumnName("nroFactura");
            entity.Property(e => e.Observ)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("observ");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precioUnitario");

            entity.HasOne(d => d.NroFacturaNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.NroFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_nroFactura");
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.HasKey(e => e.IdEmpleado).HasName("PK__Empleado__5295297C736FC0BC");

            entity.Property(e => e.IdEmpleado).HasColumnName("idEmpleado");
            entity.Property(e => e.ApeEmp)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("apeEmp");
            entity.Property(e => e.Dni).HasColumnName("dni");
            entity.Property(e => e.Domicilio)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("domicilio");
            entity.Property(e => e.Estado).HasColumnName("estado");
            entity.Property(e => e.NomEmp)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("nomEmp");
            entity.Property(e => e.Teléfono)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("teléfono");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.NroFactura).HasName("PK__Facturas__7E5F42C6FB67D997");

            entity.Property(e => e.NroFactura).HasColumnName("nroFactura");
            entity.Property(e => e.FechaFactura).HasColumnName("fechaFactura");
            entity.Property(e => e.IdCliente).HasColumnName("idCliente");
            entity.Property(e => e.IdEmpleado).HasColumnName("idEmpleado");
            entity.Property(e => e.TipoFactura)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipoFactura");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_idCliente");

            entity.HasOne(d => d.IdEmpleadoNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdEmpleado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_idEmpleado");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.IdProducto).HasName("PK__Producto__07F4A132056D3526");

            entity.Property(e => e.IdProducto).HasColumnName("idProducto");
            entity.Property(e => e.ContenidoCantidad)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("contenidoCantidad");
            entity.Property(e => e.FVencimiento).HasColumnName("fVencimiento");
            entity.Property(e => e.NombreComercial)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombreComercial");
            entity.Property(e => e.NroLote).HasColumnName("nroLote");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(14, 2)")
                .HasColumnName("precioUnitario");
            entity.Property(e => e.PrincipioActivo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("principioActivo");
            entity.Property(e => e.Proveedor)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("proveedor");
            entity.Property(e => e.Stock).HasColumnName("stock");
            entity.Property(e => e.UnidadMedida)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("unidadMedida");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.IdRol).HasName("PK__Roles__3C872F76FFB7E569");

            entity.Property(e => e.IdRol).HasColumnName("idRol");
            entity.Property(e => e.Rol)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("rol");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuarios__645723A697C071D6");

            entity.Property(e => e.IdUsuario)
                .ValueGeneratedNever()
                .HasColumnName("idUsuario");
            entity.Property(e => e.IdCredencial).HasColumnName("idCredencial");
            entity.Property(e => e.IdEmpleado).HasColumnName("idEmpleado");

            entity.HasOne(d => d.IdCredencialNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdCredencial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuarios_Credenciales");

            entity.HasOne(d => d.IdEmpleadoNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdEmpleado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuarios_Empleados");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}