// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPLogicaWebApi.DATA.Models;

public partial class Producto
{
    public int IdProducto { get; set; }

    public string NombreComercial { get; set; }

    public string PrincipioActivo { get; set; }

    public decimal ContenidoCantidad { get; set; }

    public string UnidadMedida { get; set; }

    public int NroLote { get; set; }

    public DateOnly FVencimiento { get; set; }

    public int Stock { get; set; }

    public string Proveedor { get; set; }

    public decimal PrecioUnitario { get; set; }
}