// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPLogicaWebApi.DATA.Models;

public partial class Usuario
{
    public Guid IdUsuario { get; set; }

    public Guid IdCredencial { get; set; }

    public int IdEmpleado { get; set; }

    public virtual ICollection<Autenticacion> Autenticacions { get; set; } = new List<Autenticacion>();

    public virtual Credenciale IdCredencialNavigation { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }
}